config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    get '/post_comments' => 'post_comments#index'
    get 'end_users/index_posts/:id' => 'end_users#index_posts', as: 'index_posts_end_user'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => "homes#about"
    get 'end_users/profile/:id' => 'end_users#show', as: 'profile'
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information/:id' => 'end_users#update', as: 'update_information'
    get 'end_users/check' => 'end_users#check'
    patch 'end_users/withdraw' => 'end_users#withdraw'
    get 'end_users/favorites/:id' => 'end_users#favorites', as: 'favorites_end_user'
    get 'end_users/index_posts/:id' => 'end_users#index_posts', as: 'index_posts_end_user'
    post 'end_users/:end_user_id/relationships' => 'relationships#create', as: 'end_user_relatioships'
    delete 'end_users/:end_user_id/relationships' => 'relationships#destroy'
    get 'end_users/:end_user_id/followings' => 'relationships#followings', as: 'followings'
    get 'end_users/:end_user_id/followers' => 'relationships#followers', as: 'followers'
    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'search_tag' => 'posts#search_tag'
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show]
    resources :notifications, only: [:update]
  end

  #管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  #エンドユーザー側
  devise_for :end_users, skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストログイン
  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/user.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'user.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #退会したユーザーが同じアカウントでログインできないように
  def active_for_authentication?
    super && (is_active == true)
  end

  GUEST_END_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_END_USER_EMAIL) do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name = "guestuser"
    end
  end

  def guest_end_user?
    email == GUEST_END_USER_EMAIL
  end

  #指定したユーザーをフォローする
  def follow(end_user)
    active_relationships.create(followed_id: end_user.id)
  end

  #指定したユーザーのフォローを解除する
  def unfollow(end_user)
    active_relationships.find_by(followed_id: end_user.id).destroy
  end

  #指定したユーザーをフォローしているかどうか判定
  def following?(end_user)
    followings.include?(end_user)
  end

  #Ransackによる検索機能　ユーザーネームで検索できるように
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @end_users = EndUser.all.page(params[:page]).per(5)
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    end_user = EndUser.find(params[:id])
    end_user.update(end_user_params)
    redirect_to admin_end_user_path(end_user.id)
  end

  #ユーザーごとの投稿一覧
  def index_posts
    @end_user = EndUser.find(params[:id])
    @posts = Post.where(end_user_id:params[:id]).page(params[:page]).per(8)
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name, :introduction, :email, :is_active)
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<div class="container">
    <h4 class="icon my-3"><%= image_tag @end_user.get_profile_image(80, 80) %><%= @end_user.name %>さんのプロフィール編集</h4>
    <%= form_with model: @end_user, url: admin_end_user_path(@end_user) do |f| %>
    <div class="row">
      <div class="col-4">
        <p>ID</p>
      </div>
      <div class="col-4">
        <%= @end_user.id %>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row">
      <div class="col-4">
        <%= f.label :neme, "ユーザーネーム" %>
      </div>
      <div class="col-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row">
      <div class="col-4">
        <%= f.label :introduction, "自己紹介文" %>
      </div>
      <div class="col-4">
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row">
      <div class="col-4">
        <%= f.label :email, "メールアドレス" %>
      </div>
      <div class="col-4">
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row">
      <div class="col-4">
        <%= f.label :is_active, "ステータス" %>
      </div>
      <div class="col-4">
        <%= f.radio_button :is_active, true %><%= f.label :is_active, "有効", class: "text-active" %>
        <%= f.radio_button :is_active, false %><%= f.label :is_active, "退会", class: "text-invalid" %>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row">
      <div class="col-4"></div>
      <div class="col-4"><%= f.submit "保存する", class: "btn btn-success" %></div>
      <div class="col-4"></div>
    </div>
    <% end %>
</div>

app/views/admin/end_users/index.html.erb
<div class="container">
  <div class="row">
    <h3>ユーザー一覧</h3>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>ユーザーネーム</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @end_users.each do |end_user| %>
        <tr>
          <td><%= end_user.id %></td>
          <td><%= link_to end_user.name, admin_end_user_path(end_user) %></td>
          <td><%= end_user.email %></td>
          <td>
            <% if end_user.is_active %>
            <p class="text-success"><strong>有効</strong></p>
            <% else %>
            <p class="text-muted"><strong>退会</strong></p>
            <% end %>
          </td>
        </tr>
      </tbody>
        <% end %>
    </table>
  </div>
  <%= paginate @end_users %>
</div>

app/views/admin/end_users/index_posts.html.erb
<div class="container">
  <h3><%= @end_user.name %>さんの作品一覧</h3>
  <%= render 'public/posts/list', posts: @posts %>
  <%= paginate @posts %>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="icon my-3"><%= image_tag @end_user.get_profile_image(80, 80) %><%= @end_user.name %>さんのプロフィール</h4>
    <table class="table table-borderless table-sm">
      <tr>
        <td>ID</td>
        <td><%= @end_user.id %></td>
      </tr>
      <tr>
        <td>ユーザーネーム</td>
        <td><%= @end_user.name %></td>
      </tr>
      <tr>
        <td>自己紹介文</td>
        <td><%= @end_user.introduction %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @end_user.email %></td>
      </tr>
      <tr>
        <td>ステータス</td>
        <td>
          <% if @end_user.is_active? %>
          <span class="text-active">有効</span>
          <% else %>
          <span class="text-invalid">退会</span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to "編集する", edit_admin_end_user_path(@end_user), class: "btn btn-success" %></td>
      </tr>
    </table>
    <%= link_to "全ての作品を見る>", admin_index_posts_end_user_path %>
  </div>
</div>