config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    get '/post_comments' => 'post_comments#index'
    get 'end_users/index_posts/:id' => 'end_users#index_posts', as: 'index_posts_end_user'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => "homes#about"
    get 'end_users/profile/:id' => 'end_users#show', as: 'profile'
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information/:id' => 'end_users#update', as: 'update_information'
    get 'end_users/check' => 'end_users#check'
    patch 'end_users/withdraw' => 'end_users#withdraw'
    get 'end_users/favorites/:id' => 'end_users#favorites', as: 'favorites_end_user'
    get 'end_users/index_posts/:id' => 'end_users#index_posts', as: 'index_posts_end_user'
    post 'end_users/:end_user_id/relationships' => 'relationships#create', as: 'end_user_relatioships'
    delete 'end_users/:end_user_id/relationships' => 'relationships#destroy'
    get 'end_users/:end_user_id/followings' => 'relationships#followings', as: 'followings'
    get 'end_users/:end_user_id/followers' => 'relationships#followers', as: 'followers'
    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'search_tag' => 'posts#search_tag'
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show]
    resources :notifications, only: [:update]
  end

  #管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  #エンドユーザー側
  devise_for :end_users, skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストログイン
  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :end_user
  belongs_to :post

  validates :comment, presence: true
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @post_comments = PostComment.all.page(params[:page]).per(6)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to request.referer
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<div class="container">
  <div class="row">
    <h3>コメント一覧</h3>
    <table class="table">
      <thead>
        <tr>
          <th>作品名</th>
          <th>ユーザー</th>
          <th>コメント</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @post_comments.each do |post_comment| %>
        <tr>
          <td><%= link_to post_comment.post.title, admin_post_path(post_comment.post) %></td>
          <td><%= link_to post_comment.end_user.name, admin_end_user_path(post_comment.end_user) %></td>
          <td><%= post_comment.comment %></td>
          <td><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= link_to "削除", admin_post_post_comment_path(post_id: post_comment.post_id, id: post_comment.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-danger" %></td>
        </tr>
      </tbody>
        <% end %>
    </table>
  </div>
  <%= paginate @post_comments %>
</div>