config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    get '/post_comments' => 'post_comments#index'
    get 'end_users/index_posts/:id' => 'end_users#index_posts', as: 'index_posts_end_user'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => "homes#about"
    get 'end_users/profile/:id' => 'end_users#show', as: 'profile'
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information/:id' => 'end_users#update', as: 'update_information'
    get 'end_users/check' => 'end_users#check'
    patch 'end_users/withdraw' => 'end_users#withdraw'
    get 'end_users/favorites/:id' => 'end_users#favorites', as: 'favorites_end_user'
    get 'end_users/index_posts/:id' => 'end_users#index_posts', as: 'index_posts_end_user'
    post 'end_users/:end_user_id/relationships' => 'relationships#create', as: 'end_user_relatioships'
    delete 'end_users/:end_user_id/relationships' => 'relationships#destroy'
    get 'end_users/:end_user_id/followings' => 'relationships#followings', as: 'followings'
    get 'end_users/:end_user_id/followers' => 'relationships#followers', as: 'followers'
    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'search_tag' => 'posts#search_tag'
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show]
    resources :notifications, only: [:update]
  end

  #管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  #エンドユーザー側
  devise_for :end_users, skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストログイン
  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareDrawing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2ada61ebcf.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap')
    </style>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to root_path do %>
          <div class="navbar-brand"><%= image_tag('header_logo.png') %></div>
          <% end %>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if end_user_signed_in? %>
              <li class="nav-item">
                <%= link_to profile_path(current_end_user.id), class: 'nav-link text-white' do %>
                <i class="fa-solid fa-user" style="color: #FFFFFF;"></i>マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_post_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-pen-nib " style="color: #FFFFFF;"></i>投稿する
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-palette" style="color: #FFFFFF;"></i>作品を見る
                <% end %>
              </li>
              <li class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa-solid fa-bell" style="color: #ffffff;"></i>通知
                  <span class="badge badge-danger"><%= current_end_user.notifications.where(read: false).count %></span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <% if current_end_user.notifications.where(read: false).any? %>
                    <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                    <% current_end_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                      <%= link_to notification.message, notification, method: :patch, class: "dropdown-item" %>
                    <% end %>
                  <% else %>
                    <span class="dropdown-item disabled">未読の通知はありません</span>
                  <% end %>
                </div>
              </li>
              <li class="nav-item">
                <%= link_to destroy_end_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-from-bracket" style="color: #FFFFFF;"></i>Log out
                <% end %>
              </li>
              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_end_users_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-users" style="color: #FFFFFF;"></i>ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_posts_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-palette" style="color: #FFFFFF;"></i>作品を見る
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_post_comments_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-comments" style="color: #FFFFFF;"></i>コメント一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-from-bracket" style="color: #FFFFFF;"></i>Log out
                <% end %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-paintbrush" style="color: #FFFFFF;"></i>about
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-palette" style="color: #FFFFFF;"></i>作品を見る
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_end_user_registration_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-user-plus" style="color: #FFFFFF;"></i>Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_end_user_session_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-to-bracket" style="color: #FFFFFF;"></i>Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>
      <main>
        <%= render 'public/shared/flash_message' %>
        <%= yield %>
      </main>
      <footer></footer>
  </body>
</html>